### ISSUE TITLE
Meteor 1.0.4

### ISSUE THREAD

**Issue by ilrein** [neo-technologies/meteor-reveal-js#3]
Is this package compatible with the new update? I'm not able to get reveal working following the README with this new version, though I had some success with it last version (1.0.3).

**Comment by fknipp** [comment]
I've updated the README.md, as I've had troubles with Meteor 1.1.0.2. See https://github.com/fknipp/meteor-reveal-js/tree/fixing-css until my pull request is accepted.

**Comment by julienchauveau** [comment]
@fknipp Thanks!

**Comment by fknipp** [comment]
@julienchauveau Thanks for accepting my pull request :-)
